[book]
authors = ["Matheus"]
language = "en"
multilingual = false
src = "src"
title = "VarveDB Documentation"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["src/custom.css"]
logo = "src/logo.svg"
